#!/usr/bin/env bash
process_name="$1"
caller_name="$2"
first_char="${process_name:0:1}"
rest_of_the_name="${process_name:1}"
grep_str=$(echo "[$first_char]$rest_of_the_name")
result=$(ps aux | grep -v 'isup' | grep "$(echo $grep_str)")
if [[ -n "$caller_name" ]]; then
  result=$(echo "$result" | grep -v "$caller_name")
fi
echo "$result"
