#!/bin/bash
#
# Collects password end stores it into a global $password variable
# so it is accessible to other scripts.

# Dash (-) arguments
args=()
while [ $OPTIND -le "$#" ]
do
  if getopts :gc option; then
    case $option in
      # as in grep, it reverses the filter
      (g) force_gui=1;;
      # Instead of printing in torrc digestable format, prints it
      # in human readable form with full countries names
      (c) force_cli=1;;
    esac
  else
    args+=("${!OPTIND}")
    ((OPTIND++))
  fi
done

prompt="${args[0]}"
prompt=${prompt:-"Password"}

# Determine whether we use gui prompt (zenity) or cli prompt (read).
if [[ -n "$DESKTOP_STARTUP_ID" ]]; then
  if [[ -n $force_cli ]]; then prompt_type="cli"; else prompt_type="gui"; fi
else
  if [[ -n $force_gui ]]; then prompt_type="gui"; else prompt_type="cli"; fi
fi

if [[ $prompt_type == "gui" ]]; then
  password="$(zenity --password --title "$prompt")"
else
  read -srp "$prompt: " password
fi

echo "$password"
